[workspace]
resolver = "3"
members = [
	"sfusion",
	"sfusion-cli"
]

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[workspace.dependencies]
# -- Content Formats
quick-xml = "0.37"
# -- CLI
clap = { version = "4", features = ["derive"] }
# -- Others
arboard = "3"
derive_more = { version = "2", features = ["from", "display"] }
