[package]
name = "sfusion-cli"
version = "0.1.1-WIP"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "SVG to Davinci Resolve Fusion sShapes (cli & lib)"
keywords = ["davinci-resolve","svg","parsing"]
homepage = "https://github.com/jeremychone/rust-sfusion"
repository = "https://github.com/jeremychone/rust-sfusion"

[[bin]]
name = "sfusion"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Workspace
sfusion = { version = "0.1.1-WIP", path = "../sfusion" }
# -- CLI
clap = { workspace = true }
# -- Others
arboard = { workspace = true }
derive_more = { workspace = true }
