[package]
name = "sfusion-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sfusion"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Workspace
sfusion = { path = "../sfusion" }
# -- CLI
clap = { workspace = true }
# -- Others
arboard = { workspace = true }
derive_more = { workspace = true }
