[package]
name = "sfusion"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "SVG to Davinci Resolve Fusion sShapes (cli & lib)"
keywords = ["davinci-resolve", "svg", "parsing"]
homepage = "https://github.com/jeremychone/rust-sfusion"
repository = "https://github.com/jeremychone/rust-sfusion"

[lib]
doctest = false

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Content Formats
quick-xml = { workspace = true }
# -- Others
derive_more = { workspace = true }
